### ISSUE TITLE
Consolidated design doc

### ISSUE THREAD

**Issue by ivirshup** [scverse/spatialdata#15]
In https://github.com/scverse/spatialdata/pull/14#pullrequestreview-1072395470, @kevinyamauchi suggested we collect a design document for the `SpatialData` class:

> I think we should make a short "design document" that formalizes the SpatialData design principles and gives pseudocode examples of how it would be used in an analysis pipeline. I think we have a lot of pieces of this around, but we should consolidate and make it into a document here in the repo. We should also include a glossary that defines key terms.
>
> Here is a nice example of a design document (we don't have to be this detailed/complete for now): https://napari.org/dev/naps/4-async-slicing.html

This issue is for tracking that.

(cc: @giovp @LucaMarconato)

**Comment by ivirshup** [comment]
Previous work:

* [Notes from Basel hackathon](https://hackmd.io/MPeMr2mbSRmeIzOCgwKbxw)
* Specification discussion from @giovp: scverse/spatialdata#12

**Comment by kevinyamauchi** [comment]
Nice example doc from the SOMA folks: https://github.com/single-cell-data/SOMA/blob/ac176f3628cf512660ec94748824f00cdccba452/brainstorming.md

**Comment by kevinyamauchi** [comment]
From a [zulip thread
](https://imagesc.zulipchat.com/#narrow/stream/325775-scverse-.2B-ome-.28private.29/topic/spatialdata.20grant.3A.20sync.20with.20soma.20team/near/295009447)
> where do you think that should live? Since it's kind of an extension of other specs?

For now, I think we can just do something simple such as a markdown file in a docs folder and link out the relevant specs for the on-disk layout. Eventually, I think it will get broken up into multiple parts of the doc (e.g., API docs for the spatialdata library, spec doc for the on-disk implementation).

I think the important thing is to quickly have our first version of the API laid out so that we can effectively plan the implementation and mock up pipelines to make sure it feels like it's going to work.

**Comment by LucaMarconato** [comment]
More on previous work:
* [Old on the building blocks](https://hackmd.io/uY0wPwZhQaG6HJ6OAGm0fw?both)

**Comment by kevinyamauchi** [comment]
I am closing this for now that #44 has merged 🎉
