### ISSUE TITLE
Points class metadata

### ISSUE THREAD

**Issue by giovp** [scverse/spatialdata#17]
Following #12 and #16 we should find a consensus on how to store points "metadata". 

### Visium points
- centroid coordinates as array in `adata.obsm["spatial"]`
- radius/diameter as attribute in `Points` class and stored in `.zattr` following closely how current metadata is store ome-ngff
- radius/diameter transform (one scalar value for scaling), following closely ome-zarr metadata (see https://github.com/scverse/spatialdata/blob/ea5dae66027a5769d66e31dee17f4f81d4c32a8f/spatialdata/_io/write.py#L20-L62 )

### Transcript points
- would start by just pickling the kdtree (possibly within anndata) and store path in `.zattr`

**Comment by LucaMarconato** [comment]
As I explained here https://github.com/scverse/spatialdata/issues/12#issuecomment-1238222139 at the moment I am storing the points metadata in a slightly different way due to practical coding convenience since I want to finish implementing a fully functional io and interactive viz. Then we should explore the alternatives, set a convention a refactor the code (will be quick).
