### ISSUE TITLE
Applying an Affine transformation modifies the object in a non-equivalent manner

### ISSUE THREAD

**Issue by timtreis** [scverse/spatialdata#296]
MRE
```
import math

import matplotlib.pyplot as plt
import spatialdata_plot
from spatialdata.datasets import raccoon
from spatialdata.transformations import (
    Affine,
    Identity,
    MapAxis,
    Scale,
    Sequence,
    Translation,
    get_transformation,
    get_transformation_between_coordinate_systems,
    set_transformation,
)
from spatialdata import transform

sdata = raccoon()

theta = math.pi / 6
rotation = Affine(
    [
        [math.cos(theta), -math.sin(theta), 0],
        [math.sin(theta), math.cos(theta), 0],
        [0, 0, 1],
    ],
    input_axes=("x", "y"),
    output_axes=("x", "y"),
)

set_transformation(sdata.images["raccoon"], rotation, to_coordinate_system="global")

t = get_transformation(sdata.images["raccoon"], to_coordinate_system="global")
print(t)
print("--------------------")

sdata.images["raccoon"] = transform(sdata.images["raccoon"], t)

get_transformation(sdata.images["raccoon"], to_coordinate_system="global")
```

<img width="668" alt="image" src="https://github.com/scverse/spatialdata/assets/12818242/18e4ffc8-74bc-467f-99e3-27f3db9b4185">

**Comment by giovp** [comment]
this is quite interesting, @LucaMarconato do you have any clue on why would that be the case?

**Comment by LucaMarconato** [comment]
Forgot to answer here (we discussed this in Zulip). It is because as he said the translations are not applied to the image (since we don't modify the coordinates), but also because when calling `transform()`, a rotated image is "padded" around the corners with a fill value (default 0), and this requires to prepend a new translation.

Anyway, both behaviors are weird because we don't update the xarray coordinates, but after the transformation refactoring this will be addressed.
