### ISSUE TITLE
Discussion: unifying Points and Circles

### ISSUE THREAD

**Issue by LucaMarconato** [scverse/spatialdata#46]
It may make sense in the future to unify Points and Circles. This requires the support for multiple tables, so for the moment we keep the two objects separate and allow Points to contain feature annotation.

Related discussions
- https://github.com/scverse/spatialdata/issues/43
- https://github.com/scverse/spatialdata/issues/45

**Comment by giovp** [comment]
during work with IO I noticed a missing specification for points that I think we should account for.
In particular, `nanostring cosmx` we have a single large points table with a key `fov` which corresponds to the `REGION_KEY` for labels and table. The same points table also has information on e.g. the cell_id those points equals to (e.g. i rows have cell_ID=="1" which means that those transcripts belong to the cell "1").

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/25887487/214016932-79c74821-f46e-43b2-94fe-107e331293ff.png">


As of now, none of this information is really used by the Points specifications and I think it's a missed opportunity. Therefore, I would suggest the following change in the specification to use such information:

- A `Points` table should refer to only 1 coordinate system, practically behaving like `Shapes` table. This means that in the above case, the single large table would be split in N `Points` table with N=# unique regions (as labels, shapes or else, in this case, labels). This would also allow having one or multiple coordinates transform to the `Points` tables, which would not be possible in the large single-table case.
- A `Points` table *MAY* be annotated with additional metadata such as `instance_key` (the cell_id). `region` and `region_key` instead are superfluous since it'd already be handled by the coordinate system.

thoughts @scverse/spatialdata ?

**Comment by LucaMarconato** [comment]
I agree 100% with the first point. I would also proceed with the second because it seems to me a clean way to solve a challenge that we have now. But in the long term we should consider the approach described by @ivirshup in the Munich hackathon of using a "MUON-like" table and specifying these kind of relationships in `obsp`.

**Comment by kevinyamauchi** [comment]
I am closing since we have made the initial implementation. We can open a new issue if we wish to re-visit the design.
