### ISSUE TITLE
Adding New Shapes Layer Raises Terse Exception

### ISSUE THREAD

**Issue by jeffquinn-msk** [scverse/spatialdata#469]
I have a geopandas object with a Polygon geometry column (representing cell segmentation). I attempt to add it to my xenium-project-derived SD object:

```
sd = spatialdata_io.xenium(args.xenium_dir)

# Load the segmentation shapefile
seg = geopandas.read_parquet(args.segmentation)

sd.shapes["custom_cell_segmentation"] = seg
```

I get a terse exception:

```
Traceback (most recent call last):
  File "/usr/local/bin/create_sd", line 30, in <module>
    main()
  File "/usr/local/bin/create_sd", line 26, in main
    sd.write(args.output)
  File "/usr/local/lib/python3.10/site-packages/spatialdata/_core/spatialdata.py", line 1054, in write
    raise e
  File "/usr/local/lib/python3.10/site-packages/spatialdata/_core/spatialdata.py", line 1041, in write
    write_shapes(
  File "/usr/local/lib/python3.10/site-packages/spatialdata/_io/io_shapes.py", line 87, in write_shapes
    assert t is not None
AssertionError
```

I suppose I am supposed to use ```ShapesModel.parse(gdf, transformations={"aligned": Identity()})``` but its not very clear to me from the documentation. Would be nice to cover this use case more explicitly..

Small software engineering nit: we shouldn't be using `assert` keyword in non-test code, users can disable these assertions if Python interpreter is invoked with the `-O` flag

**Comment by LucaMarconato** [comment]
Hi @jeffquinn-msk thanks for reporting. Yes, it's as you described: the objects passed to `SpatialData` must pass validation, and one way to do this is to call the parser. 

I agree with you that the error message should be clearer; I have to double check but I believe that with the latest main doing `__setitem__()` calls the validator.

In any case:
- [ ] I'll verify that the validator is called when calling `__setitem__()`
- [ ] Improve the docs on this
- [ ] Add a notebook on the usage of models and IO

I won't have time to do it soon because we are working on some large PRs to then cut a release, but it will be in the roadmap.

**Comment by LucaMarconato** [comment]
Thanks also for the comment on the `assert`. That assert was added to remove a `mypy` error, I'll try to have a look into that if I have time.

**Comment by LucaMarconato** [comment]
Great! I will reopen the issue so that the TODO items on improving the docs remain visible. 

>  Sounds good, let me know if I can help with anything..

When the example notebook in the docs is ready it would be helpful if you could review it, thanks 😊

**Comment by LucaMarconato** [comment]
> - I'll verify that the validator is called when calling __setitem__()
> - Improve the docs on this
>  - Add a notebook on the usage of models and IO

I confirm, in the latest release the validator is called on `__setitem__`. I have improved the error messages of the validator by adding a suggestion to call `.parse()`. 

Also, in the docs for the `SpatialData` class I moved the indication to use `.parse()` in the beginning of the docstring, so that the explanation is in a more visible location.

Finally, I am preparing a documentation notebook which will explain the use of the models in details (see attached PR).
