### ISSUE TITLE
polygon_query: we expect at least one shape

### ISSUE THREAD

**Issue by EST09** [scverse/spatialdata#474]
Hi, 

Thank you for this package. I'm trying to extract a polygon from Xenium data. 

```type(polygon)``` returns shapely.geometry.polygon.Polygon and ```polygon``` gives the below image. 

<img width="109" alt="Screenshot 2024-03-08 at 12 11 34" src="https://github.com/scverse/spatialdata/assets/25770709/79f9cad2-9988-4d40-8181-4f21a95b6100">

However, when I try and do a polygon_query

```
cropped_sdata2 = polygon_query(
    sdata=sdata_2,
    polygons=polygon,
    target_coordinate_system="global"
)
```

I get a ```ValueError: we expect at least one shape```

Please may I just check if I'm inputting my data wrongly? Thank you!

Best wishes, 
Emily

**Comment by LucaMarconato** [comment]
Hi, thanks for reaching out on this. I believe that the error you are getting is due to a bug that we fixed here: https://github.com/scverse/spatialdata/pull/422. Unfortunately the code, which is merged in `main`, is not yet release to `pip` yet. 

We will try to cut a release the soonest as possible. Meanwhile I kindly ask you to install the `spatialdata` package directly from GitHub using `pip install git+https://github.com/scverse/spatialdata`.

Please let me know if it fixes your issue.

**Comment by LucaMarconato** [comment]
Great to hear that it worked 😊 Yes, the new implementation uses single-dispatch so the first argument should be without name, as in your fix.
