### ISSUE TITLE
Plotting cropped Spatialdata leads to polygons protruding the viewport

### ISSUE THREAD

**Issue by pakiessling** [scverse/spatialdata#644]
Hi,
making an issue as @giovp suggested.

I ran into an issue trying to visualize a specific area of my tissue.

![grafik](https://github.com/user-attachments/assets/e2f34b82-e9bf-4ba1-87f4-8213af43d94c)

Cropping Spatialdata to a specific area by polygon query included all shapes in the crop that overlap with the query by at least a pixel. This is good and alignment remains correct, however when using `spatialdata_plot` afterwards the results will be ugly.

It would be better to crop the polygons to the viewport in this case. In principle this should be easy with `geopands .clip` or `.overlay`

I tried here https://gist.github.com/pakiessling/8a82eacb28472b3121b54079d2c3e439
but was not succesful for some reason. Maybe something was off with the coordinates?

As a sidenote, I expect that plotting of subsections will be a very common task and it would be nice to have a function that takes a bounding box or a pair of coordinates and plots that area without having to do multiple manual steps.

**Comment by LucaMarconato** [comment]
Thanks for reporting and for the example. I agree that the use case of subsetting and plotting is a common one.

I propose to add a parameter to the `bounding_box_query()` function that crops the polygons instead of returning them in full. Feedback is welcome.

Regarding prioritization, while we gather feedback I'd suggest to manually adjust the limits in the plot.

Finally, regarding the workaround, I think you need to either back-transform the polygon (transform it using the inverse affine transformation used in the shapes). Basically:
1. get the transformation to aligned from the cells polygons using `get_transformation()`;
2. call `to_affine_matrix().inverse()`
3. use the `geopandas` APIs to transform the box (the matrix needs to be rearranged into a list, please consult the `geopandas` docs)

Alternatively, you can replace 2) and 3) and do everything within `spatialdata`
2a. call `my_inverse = to_affine().inverse()`
3a. parse the box using 
```python
box = ShapesModel.parse(box, transformations={'back_transformed': my_inverse})
back_transformed_box = transform(box, to_coordinate_system='back_transformed')
```

Now the coordinates are aligned and you can use `overlay`.

**Comment by pakiessling** [comment]
Adding a Parameter sounds like a very good idea!

Ty!

**Comment by LucaMarconato** [comment]
I wrote some code to reproduce this, I have posted it in the context of another issue: https://github.com/scverse/spatialdata/issues/669.

**Comment by LucaMarconato** [comment]
I implemented a solution, based on a new parameter `clip: bool = False`.
